// lib/export-utils.ts
// Professional export utility with headers, footers, and PDF support

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ExportConfig {
  title: string;
  subtitle?: string;
  filename: string;
  headers: string[];
  rows: (string | number)[][];
  dateRange?: { from: string; to: string };
  additionalInfo?: { label: string; value: string }[];
  companyName?: string;
}

const DEFAULT_COMPANY_NAME = 'SCENTOPIA';

const formatDate = (date: Date): string => {
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'Asia/Manila',
  });
};

const formatDateTime = (date: Date): string => {
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'Asia/Manila',
  });
};

// ============================================
// CSV EXPORT WITH PROFESSIONAL FORMATTING
// ============================================
export function exportToCSV(config: ExportConfig): void {
  const {
    title,
    subtitle,
    filename,
    headers,
    rows,
    dateRange,
    additionalInfo,
    companyName = DEFAULT_COMPANY_NAME,
  } = config;

  const now = new Date();
  const csvRows: string[] = [];
  const colCount = headers.length;

  // Helper to create separator row
  const createSeparator = (char: string = '-') => {
    return Array(colCount).fill(`"${char.repeat(20)}"`).join(',');
  };

  // Helper to create empty row spanning all columns
  const emptyRow = () => Array(colCount).fill('""').join(',');

  // Helper to create a centered text row (text in first cell, rest empty)
  const centeredRow = (text: string) => {
    const cells = [`"${text}"`];
    for (let i = 1; i < colCount; i++) cells.push('""');
    return cells.join(',');
  };

  // Helper to create a label-value row
  const labelValueRow = (label: string, value: string) => {
    const cells = [`"${label}"`, `"${value}"`];
    for (let i = 2; i < colCount; i++) cells.push('""');
    return cells.join(',');
  };

  // ═══════════════════════════════════════════
  // REPORT HEADER
  // ═══════════════════════════════════════════
  csvRows.push(createSeparator('═'));
  csvRows.push(centeredRow(companyName));
  csvRows.push(centeredRow(title.toUpperCase()));
  if (subtitle) {
    csvRows.push(centeredRow(subtitle));
  }
  csvRows.push(createSeparator('═'));
  csvRows.push(emptyRow());

  // ═══════════════════════════════════════════
  // REPORT INFORMATION
  // ═══════════════════════════════════════════
  csvRows.push(centeredRow('REPORT INFORMATION'));
  csvRows.push(createSeparator('-'));
  csvRows.push(labelValueRow('Report Generated', formatDateTime(now)));
  csvRows.push(labelValueRow('Report Type', title));
  if (dateRange) {
    csvRows.push(labelValueRow('Date Range', `${dateRange.from} to ${dateRange.to}`));
  }
  csvRows.push(labelValueRow('Total Records', rows.length.toLocaleString()));

  // Additional info section
  if (additionalInfo && additionalInfo.length > 0) {
    csvRows.push(emptyRow());
    csvRows.push(centeredRow('SUMMARY'));
    csvRows.push(createSeparator('-'));
    additionalInfo.forEach(info => {
      csvRows.push(labelValueRow(info.label, info.value));
    });
  }

  csvRows.push(createSeparator('-'));
  csvRows.push(emptyRow());

  // ═══════════════════════════════════════════
  // DATA TABLE
  // ═══════════════════════════════════════════
  csvRows.push(centeredRow('DATA'));
  csvRows.push(createSeparator('═'));

  // Column headers (bold effect via caps)
  csvRows.push(headers.map(h => `"${h.toUpperCase()}"`).join(','));
  csvRows.push(createSeparator('-'));

  // Data rows
  rows.forEach((row, index) => {
    csvRows.push(row.map(cell => {
      const cellStr = String(cell);
      // Escape quotes and wrap in quotes
      return `"${cellStr.replace(/"/g, '""')}"`;
    }).join(','));
  });

  // ═══════════════════════════════════════════
  // REPORT FOOTER
  // ═══════════════════════════════════════════
  csvRows.push(createSeparator('═'));
  csvRows.push(emptyRow());
  csvRows.push(centeredRow(`Total Records: ${rows.length.toLocaleString()}`));
  csvRows.push(emptyRow());
  csvRows.push(createSeparator('-'));
  csvRows.push(centeredRow('END OF REPORT'));
  csvRows.push(createSeparator('-'));
  csvRows.push(emptyRow());
  csvRows.push(labelValueRow('Company', companyName));
  csvRows.push(labelValueRow('Classification', 'Confidential Business Report'));
  csvRows.push(labelValueRow('Report ID', `RPT-${now.getTime()}`));
  csvRows.push(labelValueRow('Generated By', 'System Auto-Generated'));
  csvRows.push(emptyRow());
  csvRows.push(centeredRow('For questions or concerns, please contact the system administrator.'));

  // Create and download the file
  const csvContent = csvRows.join('\n');
  const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' }); // BOM for Excel
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}_${now.toISOString().split('T')[0]}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}

// ============================================
// PDF EXPORT WITH HEADERS/FOOTERS
// ============================================
export function exportToPDF(config: ExportConfig): void {
  const {
    title,
    subtitle,
    filename,
    headers,
    rows,
    dateRange,
    additionalInfo,
    companyName = DEFAULT_COMPANY_NAME,
  } = config;

  const now = new Date();
  const doc = new jsPDF({
    orientation: rows[0]?.length > 6 ? 'landscape' : 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  // === HEADER ===
  // Company name
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(212, 175, 55); // Gold color
  doc.text(companyName, pageWidth / 2, 20, { align: 'center' });

  // Title
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(title, pageWidth / 2, 30, { align: 'center' });

  // Subtitle
  if (subtitle) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(subtitle, pageWidth / 2, 37, { align: 'center' });
  }

  // Divider line
  doc.setDrawColor(212, 175, 55);
  doc.setLineWidth(0.5);
  doc.line(margin, 42, pageWidth - margin, 42);

  // Report info
  let infoY = 48;
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.setFont('helvetica', 'normal');

  doc.text(`Generated: ${formatDateTime(now)}`, margin, infoY);
  infoY += 5;

  if (dateRange) {
    doc.text(`Date Range: ${dateRange.from} to ${dateRange.to}`, margin, infoY);
    infoY += 5;
  }

  if (additionalInfo) {
    additionalInfo.forEach(info => {
      doc.text(`${info.label}: ${info.value}`, margin, infoY);
      infoY += 5;
    });
  }

  doc.text(`Total Records: ${rows.length}`, margin, infoY);
  infoY += 8;

  // === DATA TABLE ===
  autoTable(doc, {
    head: [headers],
    body: rows.map(row => row.map(cell => String(cell))),
    startY: infoY,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 8,
      cellPadding: 3,
      textColor: [30, 30, 30],
      lineColor: [200, 200, 200],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: [212, 175, 55],
      textColor: [10, 10, 10],
      fontStyle: 'bold',
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [250, 248, 245],
    },
    didDrawPage: (data) => {
      // Footer on each page
      const pageCount = doc.getNumberOfPages();
      const currentPage = data.pageNumber;

      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);

      // Left footer
      doc.text(
        `${companyName} - Confidential Business Report`,
        margin,
        pageHeight - 10
      );

      // Right footer - page number
      doc.text(
        `Page ${currentPage} of ${pageCount}`,
        pageWidth - margin,
        pageHeight - 10,
        { align: 'right' }
      );

      // Center footer - report ID
      doc.text(
        `Report ID: RPT-${now.getTime()}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    },
  });

  // Final page footer enhancement
  const finalY = (doc as any).lastAutoTable?.finalY || infoY + 50;

  if (finalY < pageHeight - 40) {
    doc.setDrawColor(212, 175, 55);
    doc.setLineWidth(0.3);
    doc.line(margin, finalY + 10, pageWidth - margin, finalY + 10);

    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('--- End of Report ---', pageWidth / 2, finalY + 17, { align: 'center' });
    doc.text(
      'This report was automatically generated. For questions, contact the administrator.',
      pageWidth / 2,
      finalY + 22,
      { align: 'center' }
    );
  }

  // Save the PDF
  doc.save(`${filename}_${now.toISOString().split('T')[0]}.pdf`);
}

// ============================================
// UNIFIED EXPORT FUNCTION
// ============================================
export type ExportFormat = 'csv' | 'pdf';

export function exportReport(config: ExportConfig, format: ExportFormat): void {
  if (format === 'pdf') {
    exportToPDF(config);
  } else {
    exportToCSV(config);
  }
}

// ============================================
// HELPER: Create export config for common reports
// ============================================
export function createOrdersExportConfig(
  orders: any[],
  dateRange?: { from: string; to: string }
): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;
  const formatDateStr = (dateString: string) =>
    new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      timeZone: 'Asia/Manila',
    });

  return {
    title: 'Orders Report',
    subtitle: 'Complete order transaction details',
    filename: 'orders_report',
    headers: [
      'Order Number',
      'Customer Name',
      'Email',
      'Amount',
      'Order Status',
      'Payment Status',
      'Payment Method',
      'Items',
      'Date',
    ],
    rows: orders.map(order => [
      order.orderNumber,
      order.customerName,
      order.customerEmail,
      formatCurrency(order.amount),
      order.status,
      order.payment?.paymentStatus || 'N/A',
      order.payment?.paymentMethod || 'N/A',
      order.itemCount,
      formatDateStr(order.createdAt),
    ]),
    dateRange,
    additionalInfo: [
      { label: 'Total Orders', value: orders.length.toString() },
      { label: 'Total Revenue', value: formatCurrency(orders.reduce((sum, o) => sum + o.amount, 0)) },
    ],
  };
}

export function createProductsExportConfig(products: any[]): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;

  return {
    title: 'Products Report',
    subtitle: 'Product inventory and details',
    filename: 'products_report',
    headers: [
      'Product Name',
      'Category',
      'Type',
      'Price',
      'Stock',
      'Status',
    ],
    rows: products.map(product => [
      product.name,
      product.category?.name || 'Uncategorized',
      product.perfumeType,
      formatCurrency(product.price),
      product.totalStock,
      product.isActive ? 'Active' : 'Inactive',
    ]),
    additionalInfo: [
      { label: 'Total Products', value: products.length.toString() },
      { label: 'Active Products', value: products.filter(p => p.isActive).length.toString() },
    ],
  };
}

export function createInventoryExportConfig(
  items: any[],
  reportType: 'fast-moving' | 'slow-moving' | 'inventory-alerts',
  days?: number
): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;

  const titles: Record<string, string> = {
    'fast-moving': 'Fast-Moving Items Report',
    'slow-moving': 'Slow-Moving Items Report',
    'inventory-alerts': 'Inventory Alerts Report',
  };

  const subtitles: Record<string, string> = {
    'fast-moving': 'Products with highest sales velocity',
    'slow-moving': 'Products requiring attention due to low sales',
    'inventory-alerts': 'Stock levels requiring immediate attention',
  };

  return {
    title: titles[reportType],
    subtitle: subtitles[reportType] + (days ? ` (Last ${days} days)` : ''),
    filename: `${reportType}_report`,
    headers: [
      'Product Name',
      'Price',
      'Units Sold',
      'Revenue',
      'Current Stock',
      'Velocity (units/day)',
      'Days Until Stockout',
      'Status',
    ],
    rows: items.map(item => [
      item.name,
      formatCurrency(item.price),
      item.sold,
      formatCurrency(item.revenue),
      item.stock,
      item.velocity,
      item.daysLeft || 'N/A',
      item.status,
    ]),
    additionalInfo: days ? [{ label: 'Analysis Period', value: `${days} days` }] : undefined,
  };
}

// ============================================
// SALES REPORT CONFIGS
// ============================================
export function createSalesReportConfig(
  sales: any[],
  reportType: 'daily' | 'weekly' | 'monthly',
  dateRange?: { from: string; to: string }
): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;

  const titles: Record<string, string> = {
    'daily': 'Daily Sales Report',
    'weekly': 'Weekly Sales Report',
    'monthly': 'Monthly Sales Report',
  };

  const subtitles: Record<string, string> = {
    'daily': 'Sales breakdown by day',
    'weekly': 'Sales breakdown by week',
    'monthly': 'Sales breakdown by month',
  };

  const totalRevenue = sales.reduce((sum, s) => sum + (s.revenue || 0), 0);
  const totalOrders = sales.reduce((sum, s) => sum + (s.orderCount || 0), 0);

  return {
    title: titles[reportType],
    subtitle: subtitles[reportType],
    filename: `sales_${reportType}_report`,
    headers: [
      'Period',
      'Orders',
      'Revenue',
      'Average Order Value',
      'Items Sold',
    ],
    rows: sales.map(sale => [
      sale.period,
      sale.orderCount,
      formatCurrency(sale.revenue),
      formatCurrency(sale.averageOrderValue || (sale.revenue / (sale.orderCount || 1))),
      sale.itemsSold || 0,
    ]),
    dateRange,
    additionalInfo: [
      { label: 'Total Revenue', value: formatCurrency(totalRevenue) },
      { label: 'Total Orders', value: totalOrders.toLocaleString() },
      { label: 'Average Order Value', value: formatCurrency(totalRevenue / (totalOrders || 1)) },
    ],
  };
}

export function createSalesByCategoryConfig(
  categories: any[],
  dateRange?: { from: string; to: string }
): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;

  const totalRevenue = categories.reduce((sum, c) => sum + (c.revenue || 0), 0);

  return {
    title: 'Sales by Category Report',
    subtitle: 'Revenue breakdown by product category',
    filename: 'sales_by_category_report',
    headers: [
      'Category',
      'Products Sold',
      'Revenue',
      'Percentage of Total',
      'Average Price',
    ],
    rows: categories.map(cat => [
      cat.name,
      cat.productsSold || 0,
      formatCurrency(cat.revenue || 0),
      `${((cat.revenue / (totalRevenue || 1)) * 100).toFixed(1)}%`,
      formatCurrency(cat.averagePrice || 0),
    ]),
    dateRange,
    additionalInfo: [
      { label: 'Total Revenue', value: formatCurrency(totalRevenue) },
      { label: 'Categories', value: categories.length.toString() },
    ],
  };
}

export function createSalesByProductConfig(
  products: any[],
  dateRange?: { from: string; to: string }
): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;

  const totalRevenue = products.reduce((sum, p) => sum + (p.revenue || 0), 0);
  const totalSold = products.reduce((sum, p) => sum + (p.quantitySold || 0), 0);

  return {
    title: 'Sales by Product Report',
    subtitle: 'Top selling products with revenue',
    filename: 'sales_by_product_report',
    headers: [
      'Product Name',
      'Category',
      'Units Sold',
      'Revenue',
      'Average Price',
      'Percentage of Total',
    ],
    rows: products.map(prod => [
      prod.name,
      prod.category || 'Uncategorized',
      prod.quantitySold || 0,
      formatCurrency(prod.revenue || 0),
      formatCurrency(prod.averagePrice || 0),
      `${((prod.revenue / (totalRevenue || 1)) * 100).toFixed(1)}%`,
    ]),
    dateRange,
    additionalInfo: [
      { label: 'Total Revenue', value: formatCurrency(totalRevenue) },
      { label: 'Total Units Sold', value: totalSold.toLocaleString() },
      { label: 'Products', value: products.length.toString() },
    ],
  };
}

// ============================================
// ORDER REPORT CONFIGS
// ============================================
export function createOrderFulfillmentConfig(
  orders: any[],
  dateRange?: { from: string; to: string }
): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;
  const formatDateStr = (dateString: string) =>
    new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      timeZone: 'Asia/Manila',
    });

  const statusCounts = orders.reduce((acc: Record<string, number>, order) => {
    const status = order.status || 'Unknown';
    acc[status] = (acc[status] || 0) + 1;
    return acc;
  }, {});

  return {
    title: 'Order Fulfillment Report',
    subtitle: 'Orders by fulfillment status',
    filename: 'order_fulfillment_report',
    headers: [
      'Order Number',
      'Customer',
      'Amount',
      'Status',
      'Payment Status',
      'Date',
    ],
    rows: orders.map(order => [
      order.orderNumber,
      order.customerName,
      formatCurrency(order.amount),
      order.status,
      order.paymentStatus || 'N/A',
      formatDateStr(order.createdAt),
    ]),
    dateRange,
    additionalInfo: Object.entries(statusCounts).map(([status, count]) => ({
      label: `${status} Orders`,
      value: count.toString(),
    })),
  };
}

export function createCancellationsConfig(
  cancellations: any[],
  dateRange?: { from: string; to: string }
): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;
  const formatDateStr = (dateString: string) =>
    new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      timeZone: 'Asia/Manila',
    });

  const totalRefunded = cancellations.reduce((sum, c) => sum + (c.amount || 0), 0);

  return {
    title: 'Cancellations Report',
    subtitle: 'Cancelled and refunded orders',
    filename: 'cancellations_report',
    headers: [
      'Order Number',
      'Customer',
      'Amount',
      'Reason',
      'Cancelled Date',
      'Refund Status',
    ],
    rows: cancellations.map(cancel => [
      cancel.orderNumber,
      cancel.customerName,
      formatCurrency(cancel.amount),
      cancel.reason || 'Not specified',
      formatDateStr(cancel.cancelledAt || cancel.createdAt),
      cancel.refundStatus || 'Pending',
    ]),
    dateRange,
    additionalInfo: [
      { label: 'Total Cancellations', value: cancellations.length.toString() },
      { label: 'Total Refunded Amount', value: formatCurrency(totalRefunded) },
    ],
  };
}

// ============================================
// INVENTORY REPORT CONFIGS (NEW)
// ============================================
export function createStockLevelsConfig(
  products: any[],
  reportType: 'stock-levels' | 'low-stock' = 'stock-levels'
): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;

  const totalStock = products.reduce((sum, p) => sum + (p.stock || 0), 0);
  const lowStockCount = products.filter(p => p.status === 'Low Stock').length;
  const outOfStockCount = products.filter(p => p.status === 'Out of Stock').length;

  const isLowStock = reportType === 'low-stock';

  const headers = isLowStock
    ? ['Product Name', 'Category', 'Type', 'Size', 'Price', 'Current Stock', 'Status', 'Priority']
    : ['Product Name', 'Category', 'Type', 'Size', 'Price', 'Current Stock', 'Status', 'Last Updated'];

  const rows = products.map(prod => {
    const base = [
      prod.name,
      prod.category || 'Uncategorized',
      prod.perfumeType || 'Basic',
      prod.size || '—',
      formatCurrency(prod.price || 0),
      prod.stock || 0,
      prod.status || 'In Stock',
    ];
    return isLowStock ? [...base, prod.priority || 'Medium'] : [...base, prod.lastUpdated || 'N/A'];
  });

  return {
    title: isLowStock ? 'Low Stock Alert Report' : 'Stock Levels Report',
    subtitle: isLowStock ? 'Products at or below stock threshold by size' : 'Current inventory status per product size',
    filename: isLowStock ? 'low_stock_report' : 'stock_levels_report',
    headers,
    rows,
    additionalInfo: [
      { label: 'Total Rows', value: products.length.toString() },
      { label: 'Total Stock Units', value: totalStock.toLocaleString() },
      { label: 'Low Stock', value: lowStockCount.toString() },
      { label: 'Out of Stock', value: outOfStockCount.toString() },
    ],
  };
}

// ============================================
// CUSTOMER REPORT CONFIGS
// ============================================
export function createCustomerListConfig(
  customers: any[]
): ExportConfig {
  const totalOrders = customers.reduce((sum, c) => sum + (c.orderCount || 0), 0);
  const totalSpent = customers.reduce((sum, c) => sum + (c.totalSpent || 0), 0);
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;

  return {
    title: 'Customer List Report',
    subtitle: 'All customers with order summary',
    filename: 'customer_list_report',
    headers: [
      'Customer Name',
      'Email',
      'Total Orders',
      'Total Spent',
      'Average Order Value',
      'Last Order Date',
    ],
    rows: customers.map(cust => [
      cust.name,
      cust.email,
      cust.orderCount || 0,
      formatCurrency(cust.totalSpent || 0),
      formatCurrency(cust.averageOrderValue || 0),
      cust.lastOrderDate || 'Never',
    ]),
    additionalInfo: [
      { label: 'Total Customers', value: customers.length.toString() },
      { label: 'Total Orders', value: totalOrders.toLocaleString() },
      { label: 'Total Revenue', value: formatCurrency(totalSpent) },
    ],
  };
}

export function createTopCustomersConfig(
  customers: any[],
  limit?: number
): ExportConfig {
  const formatCurrency = (amount: number) => `PHP ${amount.toLocaleString()}`;
  const totalSpent = customers.reduce((sum, c) => sum + (c.totalSpent || 0), 0);

  return {
    title: 'Top Customers Report',
    subtitle: `Highest spending customers${limit ? ` (Top ${limit})` : ''}`,
    filename: 'top_customers_report',
    headers: [
      'Rank',
      'Customer Name',
      'Email',
      'Total Orders',
      'Total Spent',
      'Average Order Value',
    ],
    rows: customers.map((cust, index) => [
      index + 1,
      cust.name,
      cust.email,
      cust.orderCount || 0,
      formatCurrency(cust.totalSpent || 0),
      formatCurrency(cust.averageOrderValue || 0),
    ]),
    additionalInfo: [
      { label: 'Customers Shown', value: customers.length.toString() },
      { label: 'Combined Spending', value: formatCurrency(totalSpent) },
    ],
  };
}
