// regions.ts
export const regionProvinces = {
  luzon: [
    "PH-ABR",
    "PH-AGN",
    "PH-AUR",
    "PH-BTN",
    "PH-BTG",
    "PH-BUL",
    "PH-CAG",
    "PH-CAN",
    "PH-CAP",
    "PH-CAT",
    "PH-CAV",
    "PH-IFU",
    "PH-ILN",
    "PH-ILS",
    "PH-ISA",
    "PH-KAL",
    "PH-LAG",
    "PH-LUN",
    "PH-MNL",
    "PH-MDC",
    "PH-MDR",
    "PH-NUE",
    "PH-NUV",
    "PH-CAS",
    "PH-MAS",
    "PH-PAM",
    "PH-PAN",
    "PH-QUE",
    "PH-QUI",
    "PH-RIZ",
    "PH-ROM",
    "PH-TAR",
    "PH-TAW",
    "PH-ZMB",
    "PH-MAD",
  ],
  visayas: [
    "PH-AKL",
    "PH-ANT",
    "PH-BOH",
    "PH-CEB",
    "PH-GUI",
    "PH-ILI",
    "PH-LEY",
    "PH-NER",
    "PH-SIG",
    "PH-SOR",
    "PH-NEC",
    "PH-NER",
    "PH-NSA",
  ],
  mindanao: [
    "PH-AGS",
    "PH-APA",
    "PH-BAS",
    "PH-BUK",
    "PH-COM",
    "PH-DAV",
    "PH-DAS",
    "PH-DAO",
    "PH-DIN",
    "PH-EAS",
    "PH-LAN",
    "PH-LAS",
    "PH-MG",
    "PH-MSC",
    "PH-MSR",
    "PH-MOU",
    "PH-NCO",
    "PH-PLW",
    "PH-SAR",
    "PH-SCO",
    "PH-SLE",
    "PH-SUK",
    "PH-SLU",
    "PH-SUN",
    "PH-SUR",
    "PH-WSA",
    "PH-ZAN",
    "PH-ZAS",
    "PH-ZSI",
    "PH-CAM",
    "PH-BUK",
  ],
};

export const provinceNames: Record<string, string> = {
  "PH-ABR": "Abra",
  "PH-AGN": "Agusan del Norte",
  "PH-AGS": "Agusan del Sur",
  "PH-AKL": "Aklan",
  "PH-ALB": "Albay",
  "PH-ANT": "Antique",
  "PH-APA": "Apayao",
  "PH-AUR": "Aurora",
  "PH-BAN": "Banten",
  "PH-BAS": "Basilan",
  "PH-BTN": "Bataan",
  "PH-BTG": "Batangas",
  "PH-BEN": "Benguet",
  "PH-BIL": "Biliran",
  "PH-BOH": "Bohol",
  "PH-BUK": "Bukidnon",
  "PH-BUL": "Bulacan",
  "PH-CAG": "Cagayan",
  "PH-CAN": "Camarines Norte",
  "PH-CAS": "Camarines Sur",
  "PH-CAM": "Camiguin",
  "PH-CAP": "Capiz",
  "PH-CAT": "Catanduanes",
  "PH-CAV": "Cavite",
  "PH-CEB": "Cebu",
  "PH-COM": "Compostela Valley",
  "PH-DAV": "Davao del Norte",
  "PH-DAS": "Davao del Sur",
  "PH-DAO": "Davao Oriental",
  "PH-DIN": "Dinagat Islands",
  "PH-EAS": "Eastern Samar",
  "PH-GUI": "Guimaras",
  "PH-IFU": "Ifugao",
  "PH-ILN": "Ilocos Norte",
  "PH-ILS": "Ilocos Sur",
  "PH-ILI": "Iloilo",
  "PH-ISA": "Isabela",
  "PH-KAL": "Kalinga",
  "PH-LUN": "La Union",
  "PH-LAG": "Laguna",
  "PH-LAN": "Lanao del Norte",
  "PH-LAS": "Lanao del Sur",
  "PH-LEY": "Leyte",
  "PH-MG": "Maguindanao",
  "PH-MAD": "Marinduque",
  "PH-MAS": "Masbate",
  "PH-MNL": "Metro Manila",
  "PH-MSC": "Misamis Occidental",
  "PH-MSR": "Misamis Oriental",
  "PH-MOU": "Mountain Province",
  "PH-NEC": "Negros Occidental",
  "PH-NER": "Negros Oriental",
  "PH-NCO": "North Cotabato",
  "PH-NSA": "Northern Samar",
  "PH-NUE": "Nueva Ecija",
  "PH-NUV": "Nueva Vizcaya",
  "PH-MDC": "Occidental Mindoro",
  "PH-MDR": "Oriental Mindoro",
  "PH-PLW": "Palawan",
  "PH-PAM": "Pampanga",
  "PH-PAN": "Pangasinan",
  "PH-QUE": "Quezon",
  "PH-QUI": "Quirino",
  "PH-RIZ": "Rizal",
  "PH-ROM": "Romblon",
  "PH-WSA": "Samar",
  "PH-SAR": "Sarangani",
  "PH-SIG": "Siquijor",
  "PH-SOR": "Sorsogon",
  "PH-SCO": "South Cotabato",
  "PH-SLE": "Southern Leyte",
  "PH-SUK": "Sultan Kudarat",
  "PH-SLU": "Sulu",
  "PH-SUN": "Surigao del Norte",
  "PH-SUR": "Surigao del Sur",
  "PH-TAR": "Tarlac",
  "PH-TAW": "Tawi-Tawi",
  "PH-ZMB": "Zambales",
  "PH-ZAN": "Zamboanga del Norte",
  "PH-ZAS": "Zamboanga del Sur",
  "PH-ZSI": "Zamboanga Sibugay",
};

export type RegionType = "all" | "luzon" | "visayas" | "mindanao";

export function getProvincesByRegion(region: RegionType): string[] {
  if (region === "all") {
    return [
      ...regionProvinces.luzon,
      ...regionProvinces.visayas,
      ...regionProvinces.mindanao,
    ];
  }
  return regionProvinces[region] || [];
}
